### ISSUE TITLE
Two buttons in the helpdesk_mgmt_fieldservice_equipment

### ISSUE THREAD

**Issue by marcos-mendez** [kimenz/helpdesk#1]
Portal has 2 buttons and when a new ticket is created for some weired reason the tickets get duplicated (2 tickets are generated for a random equipment) 

Verify Issue and make testes for the HELPDESK_MGMT_FIELDSERVICE_EQUIPMENT module

**Comment by rafnixg** [comment]
@marcos-mendez review the PR #2

**Comment by rafnixg** [comment]
@marcos-mendez Close this Issue, the PR #2 solve this.

**Comment by marcos-mendez** [comment]
OK
