### ISSUE TITLE
[14.0][IMP] - Mostrar los datos del fsm.equipment de cada equipo

### ISSUE THREAD

**Issue by marcos-mendez** [kimenz/helpdesk#5]
![image](https://user-images.githubusercontent.com/38361760/208926696-7d37e93c-f979-44ca-8731-43fbdf6427b0.png)

En esta pantalla mostrar:

DATOS DEL EQUIPO:
NOMBRE FSM.EQUIPMENT
PRODUCTO
CATEGORIA
NUMERO DE SERIE
LOCAL

DATOS DEL LOCAL
NOMBRE del local
CALLE

**Comment by rafnixg** [comment]
Ya se puede cerrar este Issue, se resolvio con el PR #7
