### ISSUE TITLE
 [14.0][IMP] - Mostrar los datos del fsm.equipment service orders

### ISSUE THREAD

**Issue by marcos-mendez** [kimenz/helpdesk#6]
Un ticket puede tener varios fsm.orders. Esto ocurre porque el tecnico vá al local varias vezes y cumple con varias ordenes de servicio.

Por ejemplo

Se rompio una heladera de vacunas.

Se abre un ticket (el enfermero normalmente que cuida de las vacunas)

Enseguida con este ticket la central abre una FSM.ORDER para diagnosticar lo que se rompio y que piezas hay que comprar para substituit. 

Se cumple la FSM.ORDER y se vuelve con una STOCK REQUEST (pedido de piezas del stock)

Para enseguida abrir otra fsm.order y seguir con la instalacion de las piezas.

Estas fsm.orders no pueden ser abiertas por el cliente, pero si las puede ver. Estan relacionadas a cada uno de los tickets.

![image](https://user-images.githubusercontent.com/38361760/208927845-a21e7de6-8985-47d5-9983-551ce504c181.png)

Mostrar en el portal las fsm.orders dentro del ticket

**Comment by rafnixg** [comment]
Ya se puede cerrar este Issue, se resolvio con el PR #7
